remote_theme: mmistakes/minimal-mistakes
title: Purple Land Tornadoes
include: ["_pages"]

author:
  name: "Purple Tornadoes"
  avatar: "http://tornadoesandwhirlwinds.weebly.com/uploads/3/8/7/8/38785175/2777139_orig.jpeg"
  bio: "we like purple tornadoes
  
  author_profile: true
